config/routes.rb
Langapp::Application.routes.draw do
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'

  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  get 'pretest' => 'users#pretest', :as => 'pretest'
  get 'init' => 'users#initializeUser', :as => 'init'

  get 'click' => 'articles#on_click', :as => 'click'

  get 'fetch' => 'articles#addArticle', :as => 'fetch'

  root :to => 'sessions#new'
  
  
  resources :users, :sessions, :words, :articles, :kvectors

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation, 
:password_hash, :password_salt

  attr_accessible :knowledge_string

  has_many :kvectors, :dependent => :destroy

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username


  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :require_login, :only => :initializeUser
  
  # def require_login
  #   unless !!current_user
  #   flash[:error] = "Need to be logged in."
  #   redirect_to log_in_path
  #   end
  # end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end
  
  def pretest
    @user = current_user
  end

  # def efficientInitialzeUser
  #   @user = current_user
  #   if @user != nil
  #     word_order = Word.find(:first, :conditions => ["difficulty = ?",0]).text
  #     words = Word.find(:all, :conditions => ["difficulty <= ?",params[:difficulty]])
  #     # for word in words
  #     #   index = word_order.index(word.text)
  #     #   word_order[index] = word.text
  #     # end
  #     @user.knowledge_string = word_order
  #     @user.save

  #     redirect_to articles_path, :notice => "You have been initialized!"
  #   end

  # end

  # Initializes user's model
  def initializeUser
    @user = current_user
    if @user != nil
      words = Word.find(:all, :conditions => ["difficulty <= ?",params[:difficulty]])
    	kvs = []
    	for word in words
    	  @kvector = Kvector.new
    	  @kvector.word_id = word.id
    	  @kvector.is_known = true
    	  @kvector.view_count = 0
    	  @kvector.save

    	  kvs.push(@kvector)
    	end
    	@user.kvectors.destroy
      @user.kvectors = kvs
    	@user.save

      redirect_to articles_path, :notice => "You have been initialized!"
    end
  end
  
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= form_for @user do |f| %>
<p>
 <%= f.label :username %><br />
 <%= f.text_field :username %>
</p>

<p>
 <%= f.label :password %><br />
 <%= f.password_field :password %>
</p>

<p>
 <b>Set your privacy setting to "private" or "public"<b/>
 <%= f.label :privacy_setting %><br />
 <%= f.text_field :privacy_setting %>
</p>
<p class="button"><%= f.submit %></p>

  <% if session[:user_id] != nil %>
    <%= link_to "Home Page", users_path %>
  <% end %>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/pretest.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.min.js"></script>
  <style>
  ul { margin-left:20px; color:blue; }
  li { cursor:default; font-size: 14}
  li.active { background:black;color:white; }
  body {background-color: MistyRose;}
  span { color:red; }
  #hint{
    cursor:pointer;
  }
  .tooltip{
    margin:8px;
    padding:8px;
    border:1px solid blue;
    background-color:yellow;
    position: absolute;
    z-index: 2;
  }
  </style>

</head>
<body>

<h2>Pick a Level</h2>
<ul>

<li id='1'><%= link_to 'Level 1', init_path(:difficulty => 1) %></li><br>

<li id='2'><%= link_to 'Level 2', init_path(:difficulty => 2) %></li><br>

<li id='3'><%= link_to 'Level 3', init_path(:difficulty => 3) %></li><br>

<li id='4'><%= link_to 'Level 4', init_path(:difficulty => 4) %></li><br>

<li id='5'><%= link_to 'Level 5', init_path(:difficulty => 5) %></li><br>

<li id='6'><%= link_to 'Level 6', init_path(:difficulty => 6) %></li>

</ul>


<script>
// Functionality for level description display
var text1 = " Designed for learners who can understand and \nuse some simple Chinese characters and sentences to \ncommunicate, and prepares them for continuing their Chinese \nstudies. In HSK 1 all characters are provided along with \nPinyin.";

var text2 = " Designed for learners who can use Chinese in a \nsimple and direct manner, applying it in a basic fashion to \ntheir daily lives. In HSK 2 all characters are provided \nalong with Pinyin as well.";

var text3 = " Designed for learners who can use Chinese to \nserve the demands of their personal lives, studies and work, \nand are capable of completing most of the communicative \ntasks they experience during their Chinese tour.";

var text4 = " Designed for learners who can discuss a \nrelatively wide range of topics in Chinese and are capable \nof communicating with Chinese speakers at a high standard.";

var text5 = " Designed for learners who can read Chinese \nnewspapers and magazines, watch Chinese films and are \ncapable of writing and delivering a lengthy speech in Chinese.";

var text6 = " Designed for learners who can easily understand \nany information communicated in Chinese and are capable of \nsmoothly expressing themselves in written or oral form.";


var textList = [text1, text2, text3, text4, text5, text6];

$('#1').hover(
  function () {
    $(this).append($("<span>" + textList[0] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

$('#2').hover(
  function () {
    $(this).append($("<span>" + textList[1] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

$('#3').hover(
  function () {
    $(this).append($("<span>" + textList[2] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

$('#4').hover(
  function () {
    $(this).append($("<span>" + textList[3] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

$('#5').hover(
  function () {
    $(this).append($("<span>" + textList[4] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

$('#6').hover(
  function () {
    $(this).append($("<span>" + textList[5] + "</span>"));
  },
  function () {
    $(this).find("span:last").remove();
  }
);

</script>
</body>
</html>